[package]
name = "login"
version = "0.1.0"
edition = "2024"

[dependencies]
nix = { version = "0.26", features = ["term", "user", "signal", "process"] }
pwhash = "1.0"
serde = { version = "1.0", features = ["derive"] }
toml = "0.8"
